version: '3.2'
services:
  #main app container
  web-app:
    network_mode: bridge
    container_name: javi-system-web-app
    build:
      context: .
    image: "javi-system-web-app-image:latest"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /usr/src