version: '3.2'
services:
  #main app container
  web-app:
    container_name: javi-system-web-app
    network_mode: bridge
    build:
      context: .
    image: "javi-system-web-app-image:latest"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../.
        target: /usr/src
        
  docs:
    container_name: javi-system-docs
    image: "httpd"
    network_mode: bridge
    environment:
      - locale-gen=en_US.UTF-8  
      - LANG=en_US.UTF-8  
      - LANGUAGE=en_US:en  
      - LC_ALL=en_US.UTF-8
    ports:
      - "8081:80"
    volumes: 
      - type: bind
        source: ../javadoc
        target: /usr/local/apache2/htdocs/
    